### ISSUE TITLE
Conversion to other types?

### ISSUE THREAD

**Issue by DonaldTsang** [CanCLID/rime-loengfan#1]
It seems that https://github.com/CanCLID/rime-cantonese-schemes/tree/master/%E8%80%B6%E9%AD%AF%E6%8B%BC%E9%9F%B3%E6%96%B9%E6%A1%88 and https://github.com/CanCLID/rime-cantonese-schemes/tree/master/%E6%95%99%E8%82%B2%E5%AD%B8%E9%99%A2%E6%8B%BC%E9%9F%B3%E6%96%B9%E6%A1%88 are better for those that speak English, rather than those who want to learn the standard. Would it be good to have a converter for those types of users?

**Comment by laubonghaudoi** [comment]
否。我哋淨係會支持粵拼方案，我哋團隊建立此項目嘅初衷就係要推動粵語拼音標準化，推動所有人學粵拼。

**Comment by tanxpyox** [comment]
Sorry, but at this stage, our workgroup is fully committed to promoting Jyutping as _the_  standard for Cantonese... but on the bright side, you can take this as an opportunity to learn Jyutping!

If that really doesn't work out, you can try converting the dictionary files into other standards with [these `sed` scripts](https://github.com/CanCLID/rime-cantonese-alt-dict/tree/master/scripts) (I haven't tested them out, but I reckon they should work just fine)

**Comment by DonaldTsang** [comment]
It is the classic argument of Academic vs Common, and you know where I stand.

**Comment by laubonghaudoi** [comment]
呢個同學術定係普通大衆無關，拼音方案要標準化，就只能規定一個方案作爲標準，無論呢個標準係好定係差。正如普通話拼音（漢語拼音方案）有諸多設計缺陷，又多處違背英語母語者拼寫習慣，但係照樣成爲全世界通用標準（外語人士想學普通話考 HSK 都必考呢個拼音方案冇得揀）。我哋嘅初衷就係要將粵拼做成好似《漢語拼音》噉嘅唯一通用標準，而且目前絕大多數詞典工具都已經採用粵拼，再增加其他方案支援只會增加混亂度亦都令學習者困惑。
